/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Testimonial {
  'id' : TestimonialId,
  'content' : string,
  'name' : string,
  'role' : string,
  'timestamp' : Timestamp,
  'rating' : bigint,
}
export type TestimonialId = bigint;
export type Timestamp = bigint;
export interface _SERVICE {
  'deleteTestimonial' : ActorMethod<[TestimonialId], boolean>,
  'editTestimonial' : ActorMethod<
    [TestimonialId, string, string, string, bigint],
    boolean
  >,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'submitTestimonial' : ActorMethod<
    [string, string, string, bigint],
    TestimonialId
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];