/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TestimonialId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Testimonial = IDL.Record({
  'id' : TestimonialId,
  'content' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : Timestamp,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'deleteTestimonial' : IDL.Func([TestimonialId], [IDL.Bool], []),
  'editTestimonial' : IDL.Func(
      [TestimonialId, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'submitTestimonial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [TestimonialId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TestimonialId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Testimonial = IDL.Record({
    'id' : TestimonialId,
    'content' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : Timestamp,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'deleteTestimonial' : IDL.Func([TestimonialId], [IDL.Bool], []),
    'editTestimonial' : IDL.Func(
        [TestimonialId, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'submitTestimonial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [TestimonialId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };